<?php

use App\Models\User;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    // 'brand' =>  [
    //     'logo' => realpath(__DIR__.'/../public/svg/billing-logo.svg'),
    //     'color' => 'bg-gray-800',
    // ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Spark Date Format
    |--------------------------------------------------------------------------
    |
    | This date format will be utilized by Spark to format dates in various
    | locations within the billing portal, such as while showing invoice
    | dates. You should customize the format based on your own locale.
    |
    */

    'date_format' => 'F j, Y',

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(['required' => true]),
        Features::mustAcceptTerms(),
        Features::euVatCollection(['home-country' => 'DE']),
        Features::receiptEmails(['custom-addresses' => true]),
        // Features::topUps(['price' => env('SPARK_TOP_UP_PRICE')]),
        Features::paymentNotificationEmails(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Mennen Online Inh. Hendrik Mennen',
        'product' => 'SAPI - Ihr Shop API Converter',
        'street' => 'Weststr. 44',
        'location' => '26919 Brake',
        'phone' => '+49 4401 704 17 19',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'user' => [
            'model' => User::class,

            'trial_days' => 0,

            'default_interval' => 'monthly',

            'plans' => [
                [
                    'name' => 'Starter',
                    'short_description' => 'Ideal zum Ausprobieren: Erstellen Sie einen Shop mit bis zu 5 Endpunkten',
                    'monthly_id' => env('STRIPE_STARTER_PRICE_ID'),
                    'features' => [
                        '1 Shop',
                        'bis zu 5 Endpunkte',
                        'automatische inkrementelle Updates (optional)',
                    ],
                ],
                [
                    'name' => 'Premium',
                    'short_description' => 'Sie benötigen mehr Shops? Bis zu 5 Shops können Sie hier anlegen inkl. 10 Endpunkte je Shop',
                    'monthly_id' => env('STRIPE_PREMIUM_PRICE_ID'),
                    'features' => [
                        '5 Shops',
                        '10 Endpunkte je Shop',
                        'automatische inkrementelle Updates (optional)',
                    ],
                ],
                [
                    'name' => 'Professional',
                    'short_description' => 'Verwalten Sie bis zu 10 Shops inkl. 20 Endpunkte je Shop',
                    'monthly_id' => env('STRIPE_PROFESSIONAL_PRICE_ID'),
                    'features' => [
                        '10 Shops',
                        '20 Endpunkte je Shop',
                        'automatische inkrementelle Updates (optional)',
                    ],
                ],
                [
                    'name' => 'Enterprise',
                    'short_description' => 'Unbegrenzte Shops und Endpunkte',
                    'monthly_id' => env('STRIPE_ENTERPRICE_PRICE_ID'),
                    'features' => [
                        'Unbegrenzt Shops',
                        'Unbegrenzte Endpunkte',
                        'automatische inkrementelle Updates (optional)',
                    ],
                ],
            ],

        ],
    ],
];
